{ config, pkgs, lib, ... }:
#
# USER LAYER (Home Manager).
# The key trick: we DON'T write Hyprland/Quickshell config in Nix. We keep them
# as plain files under ../dotfiles and symlink them in. That keeps the actual
# rice 100% portable to Fedora/Arch (just `pacman -S` the packages there and
# point at the same files).
#
let
  # Absolute path to this repo *inside the VM*. `mkOutOfStoreSymlink` links the
  # LIVE files here (not a copy in the nix store), so editing a dotfile takes
  # effect immediately (Hyprland + Quickshell hot-reload) with NO rebuild.
  # ⚠️ Clone the repo to exactly this path, or change it here.
  repo = "/home/callum/ricing-test";
in
{
  home.stateVersion = "25.11";   # match system.stateVersion

  # Cursor theme (crisp, applied to Hyprland + GTK). Bibata is a clean default;
  # swap for an SVG hyprcursor theme later if you want resolution-independent scaling.
  home.pointerCursor = {
    name = "Bibata-Modern-Classic";
    package = pkgs.bibata-cursors;
    size = 24;
    gtk.enable = true;
  };

  # ---- The portable rice: symlink plain dotfiles into ~/.config ----
  # Main Hyprland config = a READ-ONLY store COPY of the repo file (copied at build time).
  # Bulletproof: Hyprland reads it directly (no `source` glob to race/fail), and can't write to
  # it (read-only /nix/store), so it can never autogenerate-clobber the repo file or break git.
  # Trade-off: editing hyprland.conf needs `nixos-rebuild switch` to take effect — no live
  # hot-reload for THIS one file. Every other dotfile still hot-reloads as before.
  xdg.configFile."hypr/hyprland.conf".source = ../dotfiles/hypr/hyprland.conf;

  xdg.configFile."quickshell/shell.qml".source =
    config.lib.file.mkOutOfStoreSymlink "${repo}/dotfiles/quickshell/shell.qml";

  xdg.configFile."foot/foot.ini".source =
    config.lib.file.mkOutOfStoreSymlink "${repo}/dotfiles/foot/foot.ini";
  xdg.configFile."fuzzel/fuzzel.ini".source =
    config.lib.file.mkOutOfStoreSymlink "${repo}/dotfiles/fuzzel/fuzzel.ini";
  xdg.configFile."mako/config".source =
    config.lib.file.mkOutOfStoreSymlink "${repo}/dotfiles/mako/config";
  xdg.configFile."ghostty/config".source =
    config.lib.file.mkOutOfStoreSymlink "${repo}/dotfiles/ghostty/config";

  # ---- Batch 1: CLI / dev rice configs ----
  xdg.configFile."starship.toml".source =
    config.lib.file.mkOutOfStoreSymlink "${repo}/dotfiles/starship.toml";
  xdg.configFile."zellij/config.kdl".source =
    config.lib.file.mkOutOfStoreSymlink "${repo}/dotfiles/zellij/config.kdl";
  xdg.configFile."nvim".source =
    config.lib.file.mkOutOfStoreSymlink "${repo}/dotfiles/nvim";

  # ---- Batch 2b: notifications / launcher / lock configs ----
  xdg.configFile."swaync/config.json".source =
    config.lib.file.mkOutOfStoreSymlink "${repo}/dotfiles/swaync/config.json";
  xdg.configFile."swaync/style.css".source =
    config.lib.file.mkOutOfStoreSymlink "${repo}/dotfiles/swaync/style.css";
  xdg.configFile."rofi/config.rasi".source =
    config.lib.file.mkOutOfStoreSymlink "${repo}/dotfiles/rofi/config.rasi";
  xdg.configFile."hypr/hyprlock.conf".source =
    config.lib.file.mkOutOfStoreSymlink "${repo}/dotfiles/hypr/hyprlock.conf";
  xdg.configFile."hypr/hypridle.conf".source =
    config.lib.file.mkOutOfStoreSymlink "${repo}/dotfiles/hypr/hypridle.conf";
  xdg.configFile."hypr/shaders/glow.frag".source =
    config.lib.file.mkOutOfStoreSymlink "${repo}/dotfiles/hypr/shaders/glow.frag";
  xdg.configFile."hypr/hyprpaper.conf".source =
    config.lib.file.mkOutOfStoreSymlink "${repo}/dotfiles/hypr/hyprpaper.conf";

  # ---- Hyprland plugins (hyprexpo + hyprbars) — loaded at startup, then reload ----
  # nixpkgs hyprlandPlugins are built against our nixpkgs Hyprland, so versions match.
  xdg.configFile."hypr/load-plugins.sh" = {
    executable = true;
    text = ''
      #!/bin/sh
      hyprctl plugin load ${pkgs.hyprlandPlugins.hyprexpo}/lib/libhyprexpo.so
      hyprctl plugin load ${pkgs.hyprlandPlugins.hyprbars}/lib/libhyprbars.so
      hyprctl reload
    '';
  };

  # ---- Mocha radial-gradient wallpaper, generated by Nix ----
  home.file."Pictures/wall.png".source = pkgs.runCommand "mocha-wall.png" { } ''
    ${pkgs.imagemagick}/bin/magick -size 2560x1440 radial-gradient:'#313244'-'#181825' $out
  '';

  # ---- User packages ----
  home.packages = with pkgs; [
    quickshell   # QML desktop shell (release from nixpkgs)
    # To use bleeding-edge Quickshell instead, enable the flake input in flake.nix
    # and swap this for: inputs.quickshell.packages.${pkgs.system}.default

    # ---- Batch 1: CLI / dev rice ----
    starship          # prompt
    fastfetch         # system info + logo
    zellij            # terminal multiplexer
    lazygit           # git TUI
    eza bat           # nicer ls / cat
    # Neovim (LazyVim) + runtime deps
    neovim
    ripgrep fd        # telescope grep / find
    gcc gnumake       # treesitter parser compilation
    nodejs            # some tools / LSPs
    unzip             # mason downloads (mason LSP *binaries* need nix-ld on NixOS)
    tree-sitter
    lua-language-server stylua   # for editing the nvim config itself
  ];

  programs.git.enable = true;

  programs.bash = {
    enable = true;
    initExtra = ''
      eval "$(starship init bash)"
      alias ls="eza --icons --group-directories-first"
      alias ll="eza -l --icons --git --group-directories-first"
      alias la="eza -la --icons --git --group-directories-first"
      alias cat="bat --paging=never"
    '';
  };
}
